#!/bin/bash
##################################################
dtsave=5
dt=$dtsave
freq_path=/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
freq_available=$(cat $freq_path)
freq_list=($(echo $freq_available | tr " " "\n" | sort -nr)) #this is an array
cores=$(($(nproc) - 1))
numfreq=$(($(echo $freq_available | wc -w) -1))
Thot=20000
Tstep=2500
temp=/sys/devices/virtual/thermal/thermal_zone11/temp
###################################################
    T0=$(cat $temp)
while [ $T0 -le 50000 ]
  do T0=$(cat $temp)
     echo temp $T0
           if [ $T0 -le $Thot ]
           then
             j=0
             f=${freq_list[0]}
           else
             K=$(($T0 - $Thot))
             j=$(($K / Tstep))
                 if [ $j -ge $numfreq ]
                  then
                   j=$numfreq
                 elif [ $j -le 0 ]
                  then
                   j=0
                 fi
     f=${freq_list[$j]}
  fi
    dt=$(echo "$dtsave / (2* $j^2 + 1)" | bc -l) #poll faster when throttling
    echo new j $j
    echo new freq $f
    sleep $dt
done


